In [1]:
import numpy as np

### 1D array

In [2]:
arr1 =  np.array([1,2,3])

In [3]:
arr1.shape

(3,)

### Multi Dimensional Array

In [10]:
arr2 =  np.array([[1,2,3],[4,5,6]])

In [11]:
arr2.shape

(2, 3)

In [12]:
arr2.size

6

In [13]:
arr2[0][1]

2

In [14]:
arr2[0,1]

2

### Slicing

In [18]:
arr2[0,1:3]

array([2, 3])

In [19]:
arr2[0:2,2]

array([3, 6])

### Mathematical Operations

In [20]:
x = np.array([[1,0],[0,1]])
y = np.array([[2,1],[1,2]])

In [21]:
z = np.add(x,y)
z

array([[3, 1],
       [1, 3]])

In [23]:
z = x *  2
z

array([[2, 0],
       [0, 2]])

In [24]:
z = x * y
z

array([[2, 0],
       [0, 2]])

In [25]:
z = np.dot(x,y)
z

array([[2, 1],
       [1, 2]])