# Numpy vs Lists

In [7]:
heights = [74,75,72,72,71] # in inches

In [8]:
heights

[74, 75, 72, 72, 71]

In [9]:
heights * 2.54 # convert heights to cm

TypeError: can't multiply sequence by non-int of type 'float'

In [10]:
import numpy as np

In [11]:
np_heights = np.array([74,75,72,72,71])

In [12]:
np_heights

array([74, 75, 72, 72, 71])

In [13]:
type(np_heights)

numpy.ndarray

In [14]:
np_heights * 2.54

array([187.96, 190.5 , 182.88, 182.88, 180.34])

# Numpy Methods and Operations

In [17]:
list_1 = [1,2,3]
list_2 = [4,5,6]

list_1 + list_2 # Concatenation


[1, 2, 3, 4, 5, 6]

In [19]:
np1 = np.array([1,2,3])
np2 = np.array([4,5,6])

np1 + np2 # Addition of each element

array([5, 7, 9])

# Working with N-D Arrays

In [20]:
np_heights

array([74, 75, 72, 72, 71])

In [21]:
type(np_heights)

numpy.ndarray