# Problem 1

Extracting Elements from Array

Description
From a given array, extract all the elements which are greater than 'm' and less than 'n'. Note: 'm' and 'n' are integer values provided as input.



Input format:

A list of integers on line one

Integer 'm' on line two

Integer 'n' on line three



Output format:

1-D array containing integers greater than 'm' and smaller than 'n'.





Sample input:

[ 1, 5, 9, 12, 15, 7, 12, 9 ] (array)

6 (m)

12 (n)



Sample output:

[ 9 7 9 ]





Sample input:

[ 1, 5, 9, 12, 15, 7, 12, 9 ]

12

6



Sample output:

[ ]

In [13]:
import numpy as np
import ast

input_list = ast.literal_eval(input())
m = int(input())
n = int(input())

array_1 = np.array(input_list)

final_array = array_1[ (array_1 > m) & (array_1 <n)]
print(final_array)

 [ 1, 5, 9, 12, 15, 7, 12, 9 ] 
 6
 12


[9 7 9]


In [17]:
# Another Solution

import numpy as np
import ast

input_list = ast.literal_eval(input())
m = int(input())
n = int(input())

array_1 = np.array(input_list)

print(array_1[np.logical_and(array_1>m, array_1<n)])

 [ 1, 5, 9, 12, 15, 7, 12, 9 ] 
 6
 12


[9 7 9]


# Problem 2

Border Rows and Columns

Description

Extract all the border rows and columns from a 2-D array.

Format:

Input: A 2-D Python list

Output: Four NumPy arrays - First column of the input array, first row of the input array, last column of the input array, last row of the input array respectively.

Example:
Input 1:
[[11,12,13,14],
 [21,22,23,24],
 [31,32,33,34]]

Output 1:
[11 21 31]
[11 12 13 14]
[14 24 34]
[31 32 33 34]

In [9]:
import ast,sys, numpy as np

input_list = ast.literal_eval(input())

array_2d = np.array(input_list)

col_first = array_2d[:,0]
row_first = array_2d[0]
col_last = array_2d[:,-1]
row_last = array_2d[-1]

print(col_first)
print(row_first)
print(col_last)
print(row_last)

 [[11,12,13,14], [21,22,23,24], [31,32,33,34]]


[11 21 31]
[11 12 13 14]
[14 24 34]
[31 32 33 34]


# Problem 3

Create border array

Description

Given a single integer n, create an (n x n) 2D array with 1 on the border and 0 on the inside.

Note: Make sure the array is of type int.

Example:

Input 1:
4

Output 1:
[[1 1 1 1]
[1 0 0 1]
[1 0 0 1]
[1 1 1 1]]

Input 2:
2

Output 2:
[[1 1] 
 [1 1]] 

In [11]:
import numpy as np

n = int(input())

border_arr = np.ones([n,n],dtype=int)
border_arr[1:-1,1:-1] = 0
print(border_arr)

 6


[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


# Problem 4

Stacking arrays

Description

Merge the three arrays provided to you to form a one 4x4 array.

[Hint: Check the function np.transpose() in the 'Manipulating Arrays' notebook provided.]



Input:

Array 1: 3*3

[[7, 13, 14],

[18, 10, 17],

[11, 12, 19]]



Array 2: 1-D array

[16, 6, 1]



Array 3: 1*4 array

[[5, 8, 4, 3]]



Output:

[[7 13 14 5]

[18 10 17 8]

[11 12 19 4]

[16 6 1 3]]

In [10]:
import ast

list_1 = ast.literal_eval(input())
list_2 = ast.literal_eval(input())
list_3 = ast.literal_eval(input())

# Import NumPy
import numpy as np

# Write your code here

list_12 = np.vstack([np.array(list_1),np.array(list_2)])
final_array = np.hstack([list_12, np.array(list_3).transpose()])

print(final_array)

 [[7, 13, 14],  [18, 10, 17],  [11, 12, 19]]
 [16, 6, 1]
 [[5, 8, 4, 3]]


[[ 7 13 14  5]
 [18 10 17  8]
 [11 12 19  4]
 [16  6  1  3]]


# Problem 5

Print Z

Description

Given a single positive integer 'n' greater than 2, create a NumPy array of size (n x n) will all zeros and ones such that the ones make a shape like 'Z'.

Examples:

Input 1:

3

Output 1:

[[1 1 1]
 [0 1 0]
 [1 1 1]]

Input 2:

5

Output 1:

[[1 1 1 1 1]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [1 1 1 1 1]]

Explanation: Notice that the 1s in the array make a shape like 'Z'.

In [20]:
import numpy as np

n = int(input())

zero_arr = np.zeros((n,n),dtype=int)
zero_arr[0,:] = 1
zero_arr[-1,:] = 1

for i in range(1,n):
    zero_arr[i,-i-1] = 1

print(zero_arr)

 7


array([[1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1]])

# Problem 6

Sort by Column

Description

Given a 2D NumPy array, sort it by the 1st column. Print the final sorted array as a NumPy array only.

Note: If two values in the 1st column are equal then the column in which the 2nd column value is lesser should come first. If the value in the second column is also the same then go to the third value and so on.

Example:

Input 1:

[[9 3 2]
 [4 0 1]
 [5 8 6]]

Output 2:

[[4 0 1]
 [5 8 6]
 [9 3 2]]

Input 2:

[[9 3 2]
 [4 0 1]
 [9 8 6]]

Output 2:

[[4 0 1]
 [9 3 2]
 [9 8 6]]

Explanation:

Example 1: Notice that the values in the first column are sorted. Also notice that the whole row should be moved and not just the individual values in the first column. For example, the row with the smallest value, i.e. 4 was moved as a whole. 

Example 2: Since this time the first row contains two 9s, the row in which the value in the second column is lesser came first.

In [17]:
import ast, numpy as np

input_list = ast.literal_eval(input()) # [[9,3,2],[4,0,1],[5,8,6]]

input_arr = np.array(input_list)

for i in range(len(input_arr[0, :])):
    input_arr = input_arr[input_arr[:,-1-i].argsort()]
    
print(input_arr)

 [[9,3,2],[4,0,1],[5,8,6]]


[[4 0 1]
 [5 8 6]
 [9 3 2]]


In [6]:
#Another sorting example

import numpy as np

datatype = [('name', 'U7'), ('age', int), ('height', int)]
people = [
    ('Alice', 25, 170), 
    ('Bob', 30, 180), 
    ('Charlie', 35, 175),
    ('Dan', 40, 175),
    ('Eeyore', 25, 180)
]
array = np.array(people, dtype = datatype)

# sort the people array on the basis of height
# if heights are equal, sort people on the basis of age
array2 = np.sort(array, order = ('height', 'age'))

print(array2)

[('Alice', 25, 170) ('Charlie', 35, 175) ('Dan', 40, 175)
 ('Eeyore', 25, 180) ('Bob', 30, 180)]
